[package]
name = "worktrace"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]
name = "worktrace"
path = "src/lib.rs"

[[bin]]
name = "worktrace"
path = "src/main.rs"

[dependencies]
