[package]
name = "worktrace_generator"
description = "Code generating utilities for the worktrace crate."
repository = "https://github.com/worktrace/app"
license = "MulanPSL-2.0"
version = "0.1.1"
edition = "2024"
include = [
  "/src",
  "/Cargo.toml",
  "/CONTRIBUTORS.yaml",
  "/LICENSE",
  "/README.md",
]

[lib]
crate-type = ["lib"]
name = "worktrace_generator"
path = "src/lib.rs"

[dependencies]
