name: release

on:
  push: { tags: ["v[0-9]+.[0-9]+.[0-9]+*"] }

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install proto compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler

      - run: cargo build
      - name: create release
        run: "gh release create ${{ github.ref_name }} \
          --title ${{ github.ref_name }} \
          --notes-file .changelog.md"
